# Makefile.include
# Platform-dependent settings for Q4
#

#CC = icc
CC = gcc

COPTFLAGS = -O2
#COPTFLAGS = -g

CPPFLAGS = 

#CFLAGS = $(COPTFLAGS)
CFLAGS = -Wall $(COPTFLAGS)

#LINKER = icc
LINKER = gcc

LDFLAGS = -lm -lpthread


